# Generated by Django 3.0.7 on 2020-08-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200831_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='post images/'),
        ),
    ]
