# Generated by Django 3.0.7 on 2020-09-01 20:09

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200901_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='post images/', validators=[blog.validators.validate_file_type]),
        ),
    ]
