# Generated by Django 3.0.7 on 2020-09-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='restrict_comments',
            field=models.BooleanField(default=False),
        ),
    ]
